import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Dashboard from "../design-system/organisms/Dashboard";
import SampleChart from "../design-system/molecules/DashboardChart";
import Hero from "../design-system/organisms/Hero";
import PageWrapper from "../design-system/atoms/PageWrapper";

const Home: NextPage = () => {
  const [dashboardData, setDashboardData] = useState([]);
  const [chatdData, setChartData] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchData = () => {
    const dashboardApi = "https://chsb.my-test-domain.website/chsb-metrics";
    const chartApi = "https://chsb.my-test-domain.website/chsb-price-month";

    const getDashboardData = axios.get(dashboardApi);
    const getChartData = axios.get(chartApi);

    axios.all([getDashboardData, getChartData]).then(
      axios.spread((...allData) => {
        const allDataDashboard = allData[0].data;
        const allChart = allData[1].data;

        setDashboardData(allDataDashboard);
        setChartData(allChart);

        setIsLoading(false);
      })
    );
  };

  useEffect(() => {
    setIsLoading(true);
    fetchData();
  }, []);

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (!dashboardData) {
    return <p>No data to show</p>;
  }

  return (
    <section className={styles.container}>
      <Head>
        <title>Dashboard app</title>
        <meta
          property="og:description"
          content="Generated by create next app"
          key="description"
        />
        <meta property="og:title" content="My newer title" key="title" />
        <meta property="og:image" content="/cover.png" key="image" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero chartData={chatdData} />
        <Dashboard dashboard={dashboardData} />
      </main>
    </section>
  );
};

export default Home;
