import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Dashboard from "./Dashboard";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard app</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="My new title" key="title" />
        <meta property="og:image" content="/cover.png" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/TTCommons-ExtraLight.woff2"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/TTCommons-Light.woff2"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/TTCommons-Thin.woff2"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/TTCommons-Regular.woff2"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/TTCommons-DemiBold.woff2"
          as="font"
          crossOrigin=""
        />
      </Head>

      <main className={styles.main}>
       <Dashboard />
      </main>
 
    </div>
  );
};

export default Home;
